const RESTART_DEBOUNCE = 300;
const MOCK_HEADER_NAME = 'x-api-mockup-server';

const LOG_FRAME_BLOCKS = '═║╔╗╚╝';
const LOG_LINE_MARK_CHAR = LOG_FRAME_BLOCKS[0];
const LOG_LINE_PREFIX_BASE_CHARS = LOG_LINE_MARK_CHAR + LOG_LINE_MARK_CHAR;
const LOG_LINE_PREFIX_CHARS = LOG_LINE_PREFIX_BASE_CHARS + ' ';
const LOG_LINE_PREFIX_COLOR = 'green';
const LOG_LINK_COLOR = LOG_LINE_PREFIX_COLOR;

const LOG_TIME_FORMAT = 'HH:mm:ss.SSS';

const HPM_PREFIX = '[HPM]';
const HPM_SUPPRESSED_MSGS = [
  HPM_PREFIX + ' Proxy created',
  HPM_PREFIX + ' Subscribed to',
  HPM_PREFIX + ' server close signal',
  /* HPM_PREFIX + ' Upgrade event' */
];

const LEFT_PAD = '   ';
const NEW_LINE = '\n';

module.exports = {
  RESTART_DEBOUNCE,
  MOCK_HEADER_NAME,
  LOG_FRAME_BLOCKS,
  LOG_LINE_MARK_CHAR,
  LOG_LINE_PREFIX_BASE_CHARS,
  LOG_LINE_PREFIX_CHARS,
  LOG_LINE_PREFIX_COLOR,
  LOG_LINK_COLOR,
  LOG_TIME_FORMAT,
  HPM_PREFIX,
  HPM_SUPPRESSED_MSGS,
  LEFT_PAD,
  NEW_LINE,
};
