const RESTART_DEBOUNCE = 300;
const MOCK_HEADER_NAME = 'x-api-mockup-server';
const LOG_LINE_MARK_CHAR = '═';
const LOG_LINE_PREFIX_BASE_CHARS = LOG_LINE_MARK_CHAR + LOG_LINE_MARK_CHAR;
const LOG_LINE_PREFIX_CHARS = LOG_LINE_PREFIX_BASE_CHARS + ' ';
const LOG_LINE_PREFIX_COLOR = 'green';
const LOG_LINK_COLOR = LOG_LINE_PREFIX_COLOR;
const LOG_TIME_FORMAT = 'HH:mm:ss.SSS';
const HPM_PREFIX = '[HPM]';

module.exports = {
  RESTART_DEBOUNCE,
  MOCK_HEADER_NAME,
  LOG_LINE_MARK_CHAR,
  LOG_LINE_PREFIX_BASE_CHARS,
  LOG_LINE_PREFIX_CHARS,
  LOG_LINE_PREFIX_COLOR,
  LOG_LINK_COLOR,
  LOG_TIME_FORMAT,
  HPM_PREFIX,
};
