const LOG_LINE_PREFIX_CHARS = '=== ';

const LOG_LINE_PREFIX_COLOR = 'green';

const LOG_LINK_COLOR = LOG_LINE_PREFIX_COLOR;

module.exports = {
  LOG_LINE_PREFIX_CHARS,
  LOG_LINE_PREFIX_COLOR,
  LOG_LINK_COLOR,
};
